'use strict'

const Env = use('Env')

module.exports = {
  stockResultCompare: Env.get('LOTTERY_STOCK_COMPARE', 1),

  stockSlug: {
    lottoone: {
      11: 'laos',
      12: 'malaysia',
      13: 'vietnam',
      // 14: 'vietnam_vip',
      15: 'vietnam_special',
      18: 'laos_star',
      // 21: 'thai_morning',
      // 22: 'thai_noon',
      // 23: 'thai_afternoon',
      24: 'thai_evening',
      25: 'japan_morning',
      26: 'japan_afternoon',
      27: 'hongkong_morning',
      28: 'hongkong_afternoon',
      29: 'china_morning',
      30: 'china_afternoon',
      31: 'korea',
      32: 'taiwan',
      33: 'singapore',
      34: 'india',
      35: 'egypt',
      36: 'germany',
      37: 'england',
      38: 'russia',
      39: 'america',
      91: 'gsb'
      // 40: '',
    },
    ltobet: {
      11: 'laos',
      12: 'malaysia',
      13: 'vietnam',
      21: 'thai_morning',
      22: 'thai_noon',
      23: 'thai_afternoon',
      24: 'thai_evening',
      25: 'japan_morning',
      26: 'japan_afternoon',
      27: 'hongkong_morning',
      28: 'hongkong_afternoon',
      29: 'china_morning',
      30: 'china_afternoon',
      31: 'korea',
      32: 'taiwan',
      33: 'singapore',
      34: 'india',
      35: 'egypt',
      36: 'germany',
      37: 'england',
      38: 'russia',
      39: 'america',
      // 40: '',
    },
    dnabet: {
      301: 'taiwan',
      302: 'korea',
      303: 'japan_morning',
      304: 'japan_afternoon',
      305: 'china_morning',
      306: 'china_afternoon',
      307: 'hongkong_morning',
      308: 'hongkong_afternoon',
      309: 'singapore',
      310: 'thai_evening',
      311: 'india',
      312: 'egypt',
      313: 'russia',
      314: 'germany',
      315: 'england',
      316: 'america',
      317: 'laos',
      318: 'laos_star',
      319: 'vietnam',
      320: 'vietnam_special',
      321: 'vietnam_vip',
      321: 'malaysia',
      // : 'thai_morning',
      // : 'thai_noon',
      // : 'thai_afternoon',
      // : '',
    },
    lotto432: {
      'ลาว': 'laos',
      'มาเลย์': 'malaysia',
      'ฮานอย': 'vietnam',
      'ฮานอยพิเศษ': 'vietnam_special',
      'ฮานอย_VIP': 'vietnam_vip',
      // 21: 'thai_morning',
      // 22: 'thai_noon',
      // 23: 'thai_afternoon',
      // 24: 'thai_evening',
      'หุ้นนิเคอิเช้า': 'japan_morning',
      'หุ้นนิเคอิบ่าย': 'japan_afternoon',
      'ฮั่งเส็งเช้า': 'hongkong_morning',
      'ฮั่งเส็งบ่าย': 'hongkong_afternoon',
      'จีนเช้า': 'china_morning',
      'จีนบ่าย': 'china_afternoon',
      'หุ้นเกาหลี': 'korea',
      'ไต้หวัน': 'taiwan',
      'สิงคโปร์': 'singapore',
      'อินเดีย': 'india',
      'อียิปต์': 'egypt',
      'เยอรมัน': 'germany',
      'อังกฤษ': 'england',
      'รัสเซีย': 'russia',
      'ดาวน์โจน': 'america',
    },
    kklotto: {
      'LA': 'laos',
      'MY': 'malaysia',
      'VN': 'vietnam',
      'HC': 'vietnam_special',
      'HC2': 'vietnam_vip',
      // 21: 'thai_morning',
      // 22: 'thai_noon',
      // 23: 'thai_afternoon',
      // 24: 'thai_evening',
      'NHK0': 'japan_morning',
      'NHK1': 'japan_afternoon',
      'HSC0': 'hongkong_morning',
      'HSC1': 'hongkong_afternoon',
      'CHA0': 'china_morning',
      'CHA1': 'china_afternoon',
      'HKR': 'korea',
      'TW': 'taiwan',
      'HSG': 'singapore',
      'IND': 'india',
      'EGY': 'egypt',
      'GER': 'germany',
      'ENG': 'england',
      'RUS': 'russia',
      'DJ': 'america',
      // 'AOM': 'gsb',
      // 'BAAC': 'baac',
    },
    lottovip: {
      'หวยลาว': 'laos',
      'หวยมาเลย์': 'malaysia',
      'หวยเวียดนาม/ฮานอย': 'vietnam',
      'หวยเวียดนาม/ฮานอยพิเศษ': 'vietnam_special',
      'หวยเวียดนาม/ฮานอยVIP': 'vietnam_vip',
      // 21: 'thai_morning',
      // 22: 'thai_noon',
      // 23: 'thai_afternoon',
      // 24: 'thai_evening',
      'นิเคอิรอบเช้า': 'japan_morning',
      'นิเคอิรอบบ่าย': 'japan_afternoon',
      'ฮั่งเส็งรอบเช้า': 'hongkong_morning',
      'ฮั่งเส็งรอบบ่าย': 'hongkong_afternoon',
      'จีนรอบเช้า': 'china_morning',
      'จีนรอบบ่าย': 'china_afternoon',
      'หุ้นเกาหลี': 'korea',
      'หุ้นไต้หวัน': 'taiwan',
      'หุ้นสิงคโปร์': 'singapore',
      'หุ้นอินเดีย': 'india',
      'หุ้นอียิปต์': 'egypt',
      'หุ้นเยอรมัน': 'germany',
      'หุ้นอังกฤษ': 'england',
      'หุ้นรัสเซีย': 'russia',
      'หุ้นดาวโจนส์': 'america',
      // 'AOM': 'gsb',
      // 'BAAC': 'baac',
    }
  }
}
