'use strict'

const _ = use('lodash')

/*
|--------------------------------------------------------------------------
| LotteryCategoryPowerballSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const LotteryCategory = use('App/Models/LotteryCategory')

class LotteryCategoryPowerballSeeder {
  async run () {
    const uniqueKey = 'slug'

    const lotteryCategories = [
      // America
      {
        id: 2001,
        slug: 'america_mega_million',
        zone: 'america',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 5],
        end_delay: 0,
        end_time: '11:00',
        result_delay: 0,
				result_time: '11:00',
      },
      {
        id: 2002,
        slug: 'america_powerball',
        zone: 'america',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 3, 6],
        end_delay: 0,
        end_time: '11:00',
        result_delay: 0,
				result_time: '11:00',
      },
      // Italy
      {
        id: 2011,
        slug: 'italy_superstar',
        zone: 'italy',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 4, 5, 6],
        end_delay: 0,
        end_time: '02:00',
        result_delay: 0,
				result_time: '02:00',
      },
      {
        id: 2012,
        slug: 'italy_superenalotto',
        zone: 'italy',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 4, 5, 6],
        end_delay: 0,
        end_time: '02:00',
        result_delay: 0,
				result_time: '02:00',
      },
      // Spain
      {
        id: 2021,
        slug: 'spain_euromillions',
        zone: 'spain',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 5],
        end_delay: 0,
        end_time: '03:00',
        result_delay: 0,
				result_time: '03:00',
      },
      {
        id: 2022,
        slug: 'spain_laprimitiva',
        zone: 'spain',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 4, 6],
        end_delay: 0,
        end_time: '03:40',
        result_delay: 0,
				result_time: '03:40',
      },
      {
        id: 2023,
        slug: 'spain_elgordo',
        zone: 'spain',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [7],
        end_delay: 0,
        end_time: '03:30',
        result_delay: 0,
				result_time: '03:30',
      },
      {
        id: 2024,
        slug: 'spain_bonoloto',
        zone: 'spain',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 2, 3, 4, 5, 6, 7],
        end_delay: 0,
        end_time: '03:30',
        result_delay: 0,
				result_time: '03:30',
      },
      // Austria
      {
        id: 2031,
        slug: 'austria_euromillions',
        zone: 'austria',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 5],
        end_delay: 0,
        end_time: '03:00',
        result_delay: 0,
				result_time: '03:00',
      },
      // {
      //   id: 2032,
      //   slug: 'austria_lotto',
      //   zone: 'austria',
      //   type: 'powerball',
      //   pre_start: 0,
      //   start_time: '01:00',
      //   available_day: [3, 7],
      //   end_delay: 0,
      //   end_time: '19:17',
      //   result_delay: 0,
			// 	result_time: '19:17',
      // },
      // Europe
      {
        id: 2041,
        slug: 'europe_eurojackpot',
        zone: 'europe',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 5],
        end_delay: 0,
        end_time: '03:00',
        result_delay: 0,
				result_time: '03:00',
      },
      // Australia
      {
        id: 2051,
        slug: 'australia_supersatur',
        zone: 'australia',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [6],
        end_delay: 0,
        end_time: '17:30',
        result_delay: 0,
				result_time: '17:30',
      },
      {
        id: 2052,
        slug: 'australia_powerball',
        zone: 'australia',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [4],
        end_delay: 0,
        end_time: '17:30',
        result_delay: 0,
				result_time: '17:30',
      },
      {
        id: 2053,
        slug: 'australia_saturday',
        zone: 'australia',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [6],
        end_delay: 0,
        end_time: '17:30',
        result_delay: 0,
				result_time: '17:30',
      },
      {
        id: 2054,
        slug: 'australia_oz',
        zone: 'australia',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2],
        end_delay: 0,
        end_time: '17:30',
        result_delay: 0,
				result_time: '17:30',
      },
      {
        id: 2055,
        slug: 'australia_monday',
        zone: 'australia',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1],
        end_delay: 0,
        end_time: '17:30',
        result_delay: 0,
				result_time: '17:30',
      },
      {
        id: 2056,
        slug: 'australia_wednesday',
        zone: 'australia',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3],
        end_delay: 0,
        end_time: '17:30',
        result_delay: 0,
				result_time: '17:30',
      },
      // Hungary
      {
        id: 2061,
        slug: 'hungary_otoslotto',
        zone: 'hungary',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [6],
        end_delay: 0,
        end_time: '00:45',
        result_delay: 0,
				result_time: '00:45',
      },
      {
        id: 2062,
        slug: 'hungary_hatoslotto',
        zone: 'hungary',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [7],
        end_delay: 0,
        end_time: '22:00',
        result_delay: 0,
				result_time: '22:00',
      },
      // Japan
      {
        id: 2071,
        slug: 'japan_loto7',
        zone: 'japan',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [5],
        end_delay: 0,
        end_time: '16:45',
        result_delay: 0,
				result_time: '16:45',
      },
      {
        id: 2072,
        slug: 'japan_loto6',
        zone: 'japan',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 4],
        end_delay: 0,
        end_time: '16:45',
        result_delay: 0,
				result_time: '16:45',
      },
      {
        id: 2073,
        slug: 'japan_miniloto',
        zone: 'japan',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2],
        end_delay: 0,
        end_time: '16:45',
        result_delay: 0,
				result_time: '16:45',
      },
      // France
      {
        id: 2081,
        slug: 'france_loto',
        zone: 'france',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 3, 6],
        end_delay: 0,
        end_time: '02:35',
        result_delay: 0,
				result_time: '02:35',
      },
      // Canada
      {
        id: 2091,
        slug: 'canada_lotto649',
        zone: 'canada',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 6],
        end_delay: 0,
        end_time: '09:30',
        result_delay: 0,
				result_time: '09:30',
      },
      {
        id: 2092,
        slug: 'canada_ontario49',
        zone: 'canada',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 6],
        end_delay: 0,
        end_time: '09:30',
        result_delay: 0,
				result_time: '09:30',
      },
      // Romania
      {
        id: 2101,
        slug: 'romania_joker',
        zone: 'romania',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [4, 7],
        end_delay: 0,
        end_time: '23:15',
        result_delay: 0,
				result_time: '23:15',
      },
      {
        id: 2102,
        slug: 'romania_loto649',
        zone: 'romania',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [4, 7],
        end_delay: 0,
        end_time: '23:15',
        result_delay: 0,
				result_time: '23:15',
      },
      // New Zealand
      {
        id: 2111,
        slug: 'newzealand_powerball',
        zone: 'newzealand',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 6],
        end_delay: 0,
        end_time: '14:20',
        result_delay: 0,
				result_time: '14:00',
      },
      {
        id: 2112,
        slug: 'newzealand_lotto',
        zone: 'newzealand',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 6],
        end_delay: 0,
        end_time: '14:20',
        result_delay: 0,
				result_time: '14:20',
      },
      // Peru
      {
        id: 2121,
        slug: 'peru_kabala',
        zone: 'peru',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 4, 6],
        end_delay: 0,
        end_time: '09:00',
        result_delay: 0,
				result_time: '09:00',
      },
      {
        id: 2122,
        slug: 'peru_latinka',
        zone: 'peru',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 7],
        end_delay: 0,
        end_time: '09:00',
        result_delay: 0,
				result_time: '09:00',
      },
      // Germany
      // {
      //   id: 2131,
      //   slug: 'germany_lotto',
      //   zone: 'germany',
      //   type: 'powerball',
      //   pre_start: 0,
      //   start_time: '01:00',
      //   available_day: [3, 6],
      //   end_delay: 0,
      //   end_time: '00:25',
      //   result_delay: 0,
			// 	result_time: '00:25',
      // },
      // Ukraine
      {
        id: 2141,
        slug: 'ukraine_superloto',
        zone: 'ukraine',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 6],
        end_delay: 0,
        end_time: '03:50',
        result_delay: 0,
				result_time: '03:50',
      },
      // Philippines
      {
        id: 2151,
        slug: 'philippines_ultra',
        zone: 'philippines',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 5, 7],
        end_delay: 0,
        end_time: '20:00',
        result_delay: 0,
				result_time: '20:00',
      },
      {
        id: 2152,
        slug: 'philippines_grand',
        zone: 'philippines',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 3, 6],
        end_delay: 0,
        end_time: '20:00',
        result_delay: 0,
				result_time: '20:00',
      },
      {
        id: 2153,
        slug: 'philippines_mega',
        zone: 'philippines',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 3, 5],
        end_delay: 0,
        end_time: '20:00',
        result_delay: 0,
				result_time: '20:00',
      },
      {
        id: 2154,
        slug: 'philippines_super',
        zone: 'philippines',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 4, 7],
        end_delay: 0,
        end_time: '20:00',
        result_delay: 0,
				result_time: '20:00',
      },
      {
        id: 2155,
        slug: 'philippines_lotto',
        zone: 'philippines',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 4, 6],
        end_delay: 0,
        end_time: '20:00',
        result_delay: 0,
				result_time: '20:00',
      },
      // Mexico
      {
        id: 2161,
        slug: 'mexico_melate',
        zone: 'mexico',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [3, 5, 7],
        end_delay: 0,
        end_time: '10:15',
        result_delay: 0,
				result_time: '10:15',
      },
      {
        id: 2162,
        slug: 'mexico_melateretro',
        zone: 'mexico',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 6],
        end_delay: 0,
        end_time: '10:15',
        result_delay: 0,
				result_time: '10:15',
      },
      // {
      //   id: 2163,
      //   slug: 'mexico_chispazo',
      //   zone: 'mexico',
      //   type: 'powerball',
      //   pre_start: 0,
      //   start_time: '01:00',
      //   available_day: [1, 2, 3, 4, 5, 6, 7],
      //   end_delay: 0,
      //   end_time: '09:20',
      //   result_delay: 0,
			// 	result_time: '10:00',
      // },
      // Poland
      {
        id: 2171,
        slug: 'poland_lotto',
        zone: 'poland',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [2, 4, 6],
        end_delay: 0,
        end_time: '03:50',
        result_delay: 0,
				result_time: '03:50',
      },
      {
        id: 2172,
        slug: 'poland_minilotto',
        zone: 'poland',
        type: 'powerball',
        pre_start: 0,
        start_time: '01:00',
        available_day: [1, 2, 3, 4, 5, 6],
        end_delay: 0,
        end_time: '03:50',
        result_delay: 0,
				result_time: '03:50',
      },
    ]

    for(let i in lotteryCategories) {
      const lotteryCategory = lotteryCategories[i]
      const slug = _.get(lotteryCategory, 'slug')

      const data = await LotteryCategory.findBy('slug', slug)

      if(!_.isNull(data)) {
        continue
      }

      const lottery = await LotteryCategory.create(lotteryCategory)
      console.log('lottery: ', lottery)
    }

    // await LotteryCategory.createMany(lotteryCategories)
  }
}

module.exports = LotteryCategoryPowerballSeeder
