'use strict'

const Env = use('Env')

module.exports = {
  line_oa_account: `@688yvzfu`,
  register_button: false,
  login_button: false,

  zones: {
    huay: {
      name: 'HUAY',
      sub: 'หวย',
      register: '',
      login: 'https://huay.com/',
    },
    ltobet: {
      name: 'LTO BET',
      sub: 'แอลทีโอเบท',
      register: '',
      login: 'https://www.ltobet.com/',
    },
    thailotto: {
      name: 'THAI LOTTO',
      sub: 'ไทยล็อตโต้',
      register: '',
      login: 'https://thailotto.net/',
    },
    dnabet: {
      name: 'DNA BET',
      sub: 'ดีเอ็นเอเบท',
      register: '',
      login: 'https://www.dnabet.com/',
    },
    lottoone: {
      name: 'LOTTO ONE',
      sub: 'ล็อตโต้วัน',
      register: '',
      login: 'https://lottoone.net',
    },
    kklotto: {
      name: 'KK LOTTO',
      sub: 'เคเค ล็อตโต้',
      register: '',
      login: 'https://www.kklotto.com/',
    },
    yeslotto: {
      name: 'YES LOTTO',
      sub: 'เยส ล็อตโต้',
      register: '',
      login: 'https://www.yeslotto.com/',
    },
    movewin: {
      name: 'MOVEWINBET',
      sub: 'มูฟวินเบท',
      register: '',
      login: '',
    },
    deejai: {
      name: 'ดีใจ',
      sub: '',
      register: '',
      login: '',
    },
    settee: {
      name: 'SETTEE',
      sub: '',
      register: '',
      login: 'https://settee.asia',
    },
    jaywaii: {
      name: 'JAYWAII',
      sub: 'จ่ายไว',
      register: '',
      login: 'https://jaywii.com/',
    },
    jaosuo: {
      name: 'JAOSUO',
      sub: 'เจ้าสัว',
      register: '',
      login: 'https://www.jaosuo.com/',
    },
    huaylive: {
      name: 'HUAY LIVE',
      sub: 'หวยสด',
      register: '',
      login: 'https://www.huaysod.net/',
    },
    corehuayplus: {
      name: 'CORE HUAY PLUS',
      sub: 'คอหวยพลัส',
      register: '',
      login: 'https://corehuayplus.com/',
    },
    x4rich: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    rachahuay: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    lot9999: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    huay2525: {
      name: 'HUAY 2525',
      sub: 'หวย 2525',
      register: '',
      login: 'https://www.huay2525.com',
    },
    lottotor: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    lottovip: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    ruay: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    teng1: {
      name: 'TENG 1',
      sub: 'เต็ง 1',
      register: '',
      login: 'https://www.teng1lotto.com/',
    },
    masurebet: {
      name: 'MASUREBET',
      sub: 'มาชัวร์เบท',
      register: '',
      login: 'https://www.masurebet.com',
    },
    tamjaibet: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    cat999: {
      name: 'CAT 999',
      sub: 'แคท 999',
      register: '',
      login: 'https://cat999.co',
    },
    ruamchoke: {
      name: 'RUAMCHOKE',
      sub: 'รวมโชค',
      register: '',
      login: 'https://app.ruamchoke.com',
    },
    cat888: {
      name: 'CAT 888',
      sub: 'แคท 888',
      register: '',
      login: 'https://cat888.co/',
    },
    heng168: {
      name: 'HENG 168',
      sub: 'เฮง',
      register: '',
      login: 'https://www.heng-168.co/',
    },
    siamlotto: {
      name: 'SIAM LOTTO',
      sub: 'สยามล็อตโต้',
      register: '',
      login: 'https://siamlotto.co/',
    },
    lotto77: {
      name: 'LOTTO 77',
      sub: 'ล็อตโต้ 77',
      register: '',
      login: 'https://lotto77s.co',
    },
    luxnumber: {
      name: 'LUXNUMBER',
      sub: 'ลักซ์นัทเบอร์',
      register: '',
      login: 'https://www.luxnumber.com/',
    },
    huaylike: {
      name: 'HUAY LIKE',
      sub: 'หวยไลค์',
      register: '',
      login: 'https://huaylike.net/',
    },
    maruay159: {
      name: 'มารวย159',
      sub: '',
      register: '',
      login: '',
    },
    lottorich28: {
      name: 'LOTTORICH 28',
      sub: 'ล็อตโต้ริช 28',
      register: '',
      login: 'https://www.lottorich28.co/',
    },
    kerry899: {
      name: 'KERRY 899',
      sub: 'เคอรี่ 899',
      register: '',
      login: 'https://www.kerry899.com/',
    },
    uwin789: {
      name: 'UWIN 789',
      sub: 'ยูวิน 789',
      register: '',
      login: 'https://www.uwin789.vip/',
    },
    arawan: {
      name: 'ARAWANBET',
      sub: 'เอราวัณเบท',
      register: '',
      login: 'https://arawanbet.com/',
    },
    akelottobet: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    lottothaibet: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    lotto8gold: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    lottoheng168: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    guay77: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    choke77: {
      name: '',
      sub: '',
      register: '',
      login: '',
    },
    ruaychoke: {
      name: 'RUAYCHOKE',
      sub: 'รวยโชค',
      register: '',
      login: 'https://www.ruaychoke.com',
    },
    huay9898: {
      name: '9898 หวย',
      sub: '9898HUAY',
      register: '',
      login: 'https://9898huay.com/',
    },
    haichoke: {
      name: 'HAICHOKE',
      sub: 'ให้โชค',
      register: '',
      login: 'https://www.haichoke.com',
    },
    jakchoke: {
      name: 'JAKCHOKE',
      sub: 'แจกโชค',
      register: '',
      login: 'https://www.jakchoke.com',
    },
    taweechoke: {
      name: 'TAWEECHOKE',
      sub: 'ทวีโชค',
      register: '',
      login: 'https://www.taweechok.com',
    },
    lotto432: {
      name: 'LOTTO 432',
      sub: 'ล็อตโต้ 432',
      register: '',
      login: 'https://www.lotto432s.co',
    },
    huay95: {
      name: 'หวยออนไลน์ 95',
      sub: 'หวยออนไลน์ 95',
      register: '',
      login: 'https://www.หวยออนไลน์95.com/',
    },
  },
}